CRITICAL - 2022-04-27 12:21:02 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::get_method()
#0 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#1 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#2 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-27 13:17:01 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(738): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 738, Array)
#1 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(37): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-04-27 13:19:43 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\ci_auth\app\Models\userModel.php(15): password_hash('garv2y')
#2 C:\xampp\htdocs\ci_auth\app\Models\userModel.php(11): App\Models\userModel->passwordHash(Array)
#3 C:\xampp\htdocs\ci_auth\system\BaseModel.php(1456): App\Models\userModel->beforeInsert(Array)
#4 C:\xampp\htdocs\ci_auth\system\BaseModel.php(735): CodeIgniter\BaseModel->trigger('beforeInsert', Array)
#5 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(37): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#9 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#10 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-04-27 13:20:32 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(738): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 738, Array)
#1 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(37): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-04-27 13:21:48 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(738): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 738, Array)
#1 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(37): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-04-27 13:25:59 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(738): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 738, Array)
#1 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(38): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-04-27 13:30:36 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\ci_auth\app\Models\userModel.php(15): password_hash('garv2y')
#2 C:\xampp\htdocs\ci_auth\app\Models\userModel.php(11): App\Models\userModel->passwordHash(Array)
#3 C:\xampp\htdocs\ci_auth\system\BaseModel.php(1456): App\Models\userModel->beforeInsert(Array)
#4 C:\xampp\htdocs\ci_auth\system\BaseModel.php(735): CodeIgniter\BaseModel->trigger('beforeInsert', Array)
#5 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(38): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#9 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#10 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-04-27 13:32:58 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\ci_auth\app\Models\userModel.php(15): password_hash('garv2y')
#2 C:\xampp\htdocs\ci_auth\app\Models\userModel.php(11): App\Models\userModel->passwordHash(Array)
#3 C:\xampp\htdocs\ci_auth\system\BaseModel.php(1456): App\Models\userModel->beforeInsert(Array)
#4 C:\xampp\htdocs\ci_auth\system\BaseModel.php(735): CodeIgniter\BaseModel->trigger('beforeInsert', Array)
#5 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(38): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#9 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#10 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-04-27 13:34:03 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(738): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 738, Array)
#1 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(38): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-04-27 13:39:46 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(738): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 738, Array)
#1 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(38): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-04-27 13:41:27 --> beforeInsert is not a valid Model Event callback.
#0 C:\xampp\htdocs\ci_auth\system\BaseModel.php(1453): CodeIgniter\Database\Exceptions\DataException::forInvalidMethodTriggered('beforeInsert')
#1 C:\xampp\htdocs\ci_auth\system\BaseModel.php(735): CodeIgniter\BaseModel->trigger('beforeInsert', Array)
#2 C:\xampp\htdocs\ci_auth\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\ci_auth\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\ci_auth\app\Controllers\users.php(38): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(832): App\Controllers\users->register()
#6 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\users))
#7 C:\xampp\htdocs\ci_auth\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci_auth\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci_auth\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
